# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\programming\Ui\SteraPyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 700)
        self.frameBuildings = QtWidgets.QFrame(Dialog)
        self.frameBuildings.setGeometry(QtCore.QRect(10, 10, 391, 671))
        self.frameBuildings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBuildings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBuildings.setObjectName("frameBuildings")
        self.textBrowser = QtWidgets.QTextBrowser(self.frameBuildings)
        self.textBrowser.setGeometry(QtCore.QRect(20, 100, 361, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.fileOpenButton = QtWidgets.QPushButton(self.frameBuildings)
        self.fileOpenButton.setGeometry(QtCore.QRect(160, 260, 93, 28))
        self.fileOpenButton.setObjectName("fileOpenButton")
        self.loadFileName = QtWidgets.QLineEdit(self.frameBuildings)
        self.loadFileName.setGeometry(QtCore.QRect(120, 60, 261, 21))
        self.loadFileName.setText("")
        self.loadFileName.setObjectName("loadFileName")
        self.labelFileName = QtWidgets.QLabel(self.frameBuildings)
        self.labelFileName.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.labelFileName.setObjectName("labelFileName")
        self.labelTitle = QtWidgets.QLabel(self.frameBuildings)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelTitle_3 = QtWidgets.QLabel(self.frameBuildings)
        self.labelTitle_3.setGeometry(QtCore.QRect(10, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTitle_3.setFont(font)
        self.labelTitle_3.setObjectName("labelTitle_3")
        self.buildStartButton_1 = QtWidgets.QPushButton(self.frameBuildings)
        self.buildStartButton_1.setGeometry(QtCore.QRect(280, 630, 93, 28))
        self.buildStartButton_1.setObjectName("buildStartButton_1")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(420, 10, 391, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelFileName_2 = QtWidgets.QLabel(self.frame)
        self.labelFileName_2.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.labelFileName_2.setObjectName("labelFileName_2")
        self.loadFileName_2 = QtWidgets.QLineEdit(self.frame)
        self.loadFileName_2.setGeometry(QtCore.QRect(120, 60, 261, 21))
        self.loadFileName_2.setText("")
        self.loadFileName_2.setObjectName("loadFileName_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 100, 361, 151))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.fileOpenButton_2 = QtWidgets.QPushButton(self.frame)
        self.fileOpenButton_2.setGeometry(QtCore.QRect(160, 260, 93, 28))
        self.fileOpenButton_2.setObjectName("fileOpenButton_2")
        self.labelTitle_2 = QtWidgets.QLabel(self.frame)
        self.labelTitle_2.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTitle_2.setFont(font)
        self.labelTitle_2.setObjectName("labelTitle_2")
        self.buildStartButton_2 = QtWidgets.QPushButton(self.frame)
        self.buildStartButton_2.setGeometry(QtCore.QRect(290, 630, 93, 28))
        self.buildStartButton_2.setObjectName("buildStartButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fileOpenButton.setText(_translate("Dialog", "Open file."))
        self.labelFileName.setText(_translate("Dialog", "File name"))
        self.labelTitle.setText(_translate("Dialog", "Buildings"))
        self.labelTitle_3.setText(_translate("Dialog", "Model Settings"))
        self.buildStartButton_1.setText(_translate("Dialog", "Build start"))
        self.labelFileName_2.setText(_translate("Dialog", "File name"))
        self.fileOpenButton_2.setText(_translate("Dialog", "Open file."))
        self.labelTitle_2.setText(_translate("Dialog", "Terrain"))
        self.buildStartButton_2.setText(_translate("Dialog", "Build start"))
